server:
  port: 9000

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        # ======================
        # CANCHA
        # ======================
        - id: ms-cancha
          uri: lb://ms-cancha
          predicates:
            - Path=/canchas/**
          filters:
            - StripPrefix=1
            - AuthFilter

        # ======================
        # RESERVAS
        # ======================
        - id: ms-reserva-cancha
          uri: lb://ms-reserva-cancha
          predicates:
            - Path=/reservas/**
          filters:
            - StripPrefix=1
            - AuthFilter

        # ======================
        # UBICACION
        # ======================
        - id: ms-ubicacion
          uri: lb://ms-ubicacion
          predicates:
            - Path=/ubicaciones/**
          filters:
            - StripPrefix=1
            - AuthFilter

        # ======================
        # USUARIO
        # ======================
        - id: ms-usuario
          uri: lb://ms-usuario
          predicates:
            - Path=/usuarios/**
          filters:
            - StripPrefix=1
            - AuthFilter

        # ======================
        # AUTH (NO FILTRO)
        # ======================
        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
