server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: ms-reserva-cancha

  main:
    allow-bean-definition-overriding: true

  datasource:
    url: jdbc:mysql://localhost:3306/ms_reserva_cancha
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}
    fetch-registry: true
    register-with-eureka: true

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# ============================================
# 🔥 RESILIENCE4J — YA FUNCIONANDO
# ============================================
resilience4j:
  circuitbreaker:
    instances:
      canchaPorIdCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      usuarioPorIdCB:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

  retry:
    instances:
      canchaPorIdCB:
        maxAttempts: 3
        waitDuration: 1s
      usuarioPorIdCB:
        maxAttempts: 3
        waitDuration: 1s
